development:
  adapter: mysql2
  database: dexcodehr_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  database: dexcodehr_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  database: dexcodehr_production
  pool: 5
  username: root
  password:
